### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [JosePenaherrera/prj-rev-bwfs-tea-cozy#6]
Exceeds Expectations 🔥 

You've done a **superb** job with this project, and I have nothing but praise for the work you've produced.

See if you can come back to this project after you've learned a little bit about media queries and mobile responsiveness. If you can finish this program with multiple fully responsive websites under your belt, you're going to be exceptionally prepared to hit the ground running as a freelancer.

Awesome job, keep it up!

**Comment by JosePenaherrera** [comment]
Thanks for all the feedback Steve!

Jose
